name: Ultimate Developer Profile Generator
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-dynamic-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugins:
            - base.indepth: true
            - languages: true
            - blockchain: true
            - achievements: true
            - notable: true
          config_timezone: Asia/Dhaka
          config_display: modern
          optimize: true
          use_prebuilt_image: true
